VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "workshop_FY15"
	config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
	config.omnibus.chef_version = :latest

	config.vm.network :forwarded_port, guest: 80, host: 20080 # http
	config.vm.network :forwarded_port, guest: 8080, host: 28080 # http
	config.vm.network :forwarded_port, guest: 8180, host: 28180 # jenkins

	config.vm.synced_folder "../src", "/var/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	config.vm.provision "chef_solo" do |chef|
		chef.cookbooks_path = "../chef/site-cookbooks/"
		chef.run_list = %w[
			recipe[java]
			recipe[java::maven]
			recipe[java::spring-boot_with_maven]
			recipe[jenkins]
		]
	end

end
