VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "CentOS_6.5.3_Minimal"
	config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
	config.omnibus.chef_version = :latest

	config.vm.network :forwarded_port, guest: 3000, host: 33000 # node

	config.vm.synced_folder "../../src/final-app", "/var/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	config.vm.provision "chef_solo" do |chef|
		chef.cookbooks_path = "../../chef/site-cookbooks/"
		chef.run_list = %w[
			recipe[linux::localedef_for_UTF-8]
			recipe[linux::sudoers_for_path]
			recipe[mongodb]
			recipe[redis]
			recipe[node.js]
			recipe[node.js::express]
			recipe[node.js::pm2]
			recipe[node.js::stylus_and_nib]
			recipe[node.js::launch_final-app]
		]
	end

	# for bug of Vagrant 1.7.2
	unless Vagrant.has_plugin?('vagrant-triggers')
		# Attempt to install ourself.
		# Bail out on failure so we don't get stuck in an infinite loop.
		system('vagrant plugin install vagrant-triggers') || exit!

		# Relaunch Vagrant so the new plugin(s) are detected.
		# Exit with the same status code.
		exit system('vagrant', *ARGV)
	end

	config.trigger.before [:reload, :up], stdout: true do
		my_SYNCED_FOLDER = ".vagrant/machines/default/virtualbox/synced_folders"
		info "Trying to delete folder #{my_SYNCED_FOLDER}"
		begin
			File.delete(my_SYNCED_FOLDER)
		rescue StandardError => e
			warn "Could not delete folder #{my_SYNCED_FOLDER}."
			warn e.inspect
		end
	end
end
